# Generated by Django 5.1.7 on 2025-04-02 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField(default='Adresse inconnue')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'DVD'), ('cd', 'CD'), ('jeu', 'Jeu de plateau')], max_length=10)),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('duree_jours', models.PositiveIntegerField(default=7)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.emprunteur')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.media')),
            ],
        ),
    ]
