# Generated by Django 5.1.7 on 2025-04-04 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0003_plateaujeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateaujeu',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='EmpruntPlateauJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.emprunteur')),
                ('plateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.plateaujeu')),
            ],
        ),
    ]
